---
title: "Git It Notes"
author: "Christina Chen"
date: "2023-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial Set Up

```{bash to check what version of git you are on}
git --version
```

```{bash set your name and email}
git config --global user.name "christina"
git config --global user.email "omqchristi@gmail.com"
```

- repositories are collections of related items -- basically folders full of stuff
- git tracks everything that happens to in the folder; if things are added/deleted/changed (this is known as version control)

# Making a New Directory

```{bash make a directory named "hello-world"}
mkdir hello-world
```

[mkdir] make a directory/folder

```{bash change directory into "hello-world"}
cd hello-world
```

[cd] change directory

# Starting to Track with Git

## General Information

from now on, this script is in the "hello-world" folder, as if you have changed directory into the hello-world folder
```{bash tell git to start tracking the folder you are in right now}
git init
```

```{bash check if you are in a git repository}
git status
```

```{bash list the files in the directory you are in}
ls
```

[ls] to list all the files in the directory you are in

## Commiting Files

add a text file to see changes to the status:

```{bash after adding a text file, check the status of your repository}
git status
```

there is now 1 untracked file. add and commit it to the main branch:
1. use [git add (name of file)] to add the file or [git add .] to add all file changes
2. use [git commit -m "(insert message here)"] to commit the file

```{bash use git add and git commit to }
git add readme.txt
git commit -m "created readme file"
git status
```

## Committing Changes

the original readme.txt file has been changed, track the difference with [git diff]

``` {bash using git diff}
git diff
```

commit the new change:

```{bash commiting changes}
git add readme.txt
git commit -m "added to readme.txt"
git status
```

# Connecting to Github

```{bash adding your github account}
git config --global user.username omqchristi
git config --global user.username
```

## Setting Upstream

```{bash}
git push --set-upstream origin main
```

## Connecting Local Repository to Remote Repository

after creating a repository on github.com, connect your local hello-world repository to that one:

```{bash connecting local to remote by using a link}
git remote add origin git@github.com:omqchristi/hello-world.git
```

[git remote add (name of remote) (url from github)] linking 

```{bash to change the url}
git remote set-url origin https://github.com/omqchristi/hello-world.git
```

to double check that you did it correctly:

```{bash to check what urls the remotes are linked to}
git remote -v
```

you can have multiple remotes, but the primary one is typically named "origin".
you can have multiple branches, but the primary one is typically named "main".

````{bash push your work onto github}
git push origin main
```

[git push (name of remoted) (name of branch)]

## Forking and Cloning

```{bash cloning a remote from github to your own computer}
cd ..
git clone https://github.com/omqchristi/patchwork
```

[git clone (url from github)] 

```{bash double check your clone}
cd ../patchwork
git remote -v
```

```{bash connect the original as an upstream so you can pull changes from the original and doubel check it}
cd ../patchwork
git remote add upstream https://github.com/jlord/patchwork.git
git remote -v
```

```{bash check to see if you are in gh-pages branch}
cd ../patchwork
git status
```

```{bash create a new branch named "add-omqchristi and go into it}
cd ../patchwork
git branch add-omqchristi
git checkout add-omqchristi
```

after adding a new file with your username in the CONTRIBUTORS folder, push the change to github

```{bash}
cd ../patchwork
git add CONTRIBUTORS/add-omqchristi.txt
git commit -m "added omqchristi"
git push origin add-omqchristi
```

[git push (name of remote) (name of branch)]

## Pulling Changes

after adding reporobot, pul the changes 

```{bash pull changes}
cd ../patchwork
git pull origin add-omqchristi
```
to see changes without actualing pulling use:
[git fetch --dry-run]

## Pull Requests

to request that your changes get pulld upwards to the original repository, open a pull request on github.

## Trimming Branches

now that your changes have been pulled upstream, it's time to clean up your branches by deleting them locally and remotely

```{bash}
cd ../patchwork
git checkout gh-pages # go back to the branch you want to merge into
git merge add-omqchristi # designate what branch is being absorbed
git branch -d add-omqchristi # delete the old branch
git push origin --delete add-omqchristi
```

[git push (name of remote) --delete (name of branch)]

## Finally, Pull the upstream version for the most up-to-date version

```{bash}
cd ../patchwork
git pull upstream gh-pages
```

## Common Files in Public Repositories

1. readme files:
  - explain what the repository does
  - how to use the repository
  - and maybe how to contribute to the file
2. .gitignore is a list of files that git should not track, possibly because it has sensitive information
3. license files is the type of license your project is under. this lets other people know how and if they can use it.

```{bash}
git add git_it_notes.Rmd
git commit -m "updating Git It notes"
git push
```

